version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_MAIN_API_URL=http://localhost:5000
      - REACT_APP_SECONDARY_API_URL=http://localhost:5001
    depends_on:
      - main-api
      - secondary-api

  main-api:
    build: ./main-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  secondary-api:
    build: ./secondary-api
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py 